import { DispatchedEmail, EmailNotificationConfig, Position } from '../types';

export const DEFAULT_EMAIL_NOTIFICATION_CONFIG: EmailNotificationConfig = {
  enabled: true,
  recipientEmail: 'yemyemmthika@gmail.com',
  notifyOnMarginCall: true,
  marginCallThresholdPercent: 100,
  notifyOnLargeLoss: true,
  largeLossThresholdDollar: 40,
  largeLossThresholdPips: 20,
  notifyOnStrategySwitch: true,
  notifyOnPanicStop: true,
  notifyOnDailyDrawdownHalt: true,
  throttleMinutes: 0,
};

// Generate realistic formatted email bodies with responsive styling
export function createMarginCallEmail(
  recipient: string,
  marginLevel: number,
  equity: number,
  margin: number,
  freeMargin: number
): DispatchedEmail {
  const timestamp = Date.now();
  const dateStr = new Date(timestamp).toUTCString();

  return {
    id: `email-margin-${timestamp}-${Math.floor(Math.random() * 1000)}`,
    timestamp,
    recipient,
    subject: `🚨 [CRITICAL MARGIN CALL] Margin Level Dropped to ${marginLevel}% on MT5 Account`,
    event: 'MARGIN_CALL',
    severity: 'CRITICAL',
    status: 'DELIVERED',
    summary: `Margin level fallen to ${marginLevel}%. Equity ($${equity.toFixed(2)}) is close to used margin ($${margin.toFixed(2)}). Immediate capital or position liquidation required.`,
    meta: {
      marginLevel,
      amount: equity,
    },
    body: `
<!DOCTYPE html>
<html>
<head><style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #09090b; color: #f4f4f5; margin: 0; padding: 24px; }
  .card { max-width: 580px; margin: 0 auto; background: #18181b; border: 1px solid #ef4444; border-radius: 12px; overflow: hidden; }
  .header { background: #450a0a; border-bottom: 1px solid #ef4444; padding: 20px; }
  .badge { display: inline-block; background: #ef4444; color: #fff; font-size: 11px; font-weight: bold; padding: 4px 10px; border-radius: 9999px; text-transform: uppercase; }
  .title { margin: 12px 0 4px 0; font-size: 20px; font-weight: bold; color: #ffffff; }
  .content { padding: 24px; font-size: 14px; line-height: 1.6; color: #d4d4d8; }
  .metric-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin: 20px 0; }
  .metric-box { background: #09090b; border: 1px solid #27272a; border-radius: 8px; padding: 12px; }
  .metric-label { font-size: 11px; color: #a1a1aa; text-transform: uppercase; letter-spacing: 0.5px; }
  .metric-value { font-size: 18px; font-weight: bold; margin-top: 4px; font-family: monospace; }
  .warning-box { background: #27272a; border-left: 4px solid #f59e0b; padding: 12px 16px; border-radius: 4px; margin-top: 16px; font-size: 13px; color: #fef08a; }
  .btn { display: inline-block; background: #ef4444; color: #ffffff; text-decoration: none; padding: 10px 20px; border-radius: 6px; font-weight: bold; font-size: 13px; margin-top: 20px; text-align: center; }
  .footer { border-top: 1px solid #27272a; padding: 16px 24px; font-size: 11px; color: #71717a; text-align: center; }
</style></head>
<body>
  <div class="card">
    <div class="header">
      <span class="badge">Critical Risk Notification</span>
      <div class="title">Margin Call Warning: Level ${marginLevel}%</div>
      <div style="font-size: 12px; color: #fca5a5;">Dispatched at: ${dateStr}</div>
    </div>
    <div class="content">
      <p>Your Forex Auto-Trading Robot has detected that the account's <strong>Margin Level</strong> has dropped below the critical security threshold.</p>
      
      <div class="metric-grid">
        <div class="metric-box">
          <div class="metric-label">Current Margin Level</div>
          <div class="metric-value" style="color: #ef4444;">${marginLevel}%</div>
        </div>
        <div class="metric-box">
          <div class="metric-label">Account Equity</div>
          <div class="metric-value" style="color: #ffffff;">$${equity.toFixed(2)}</div>
        </div>
        <div class="metric-box">
          <div class="metric-label">Used Margin</div>
          <div class="metric-value" style="color: #f59e0b;">$${margin.toFixed(2)}</div>
        </div>
        <div class="metric-box">
          <div class="metric-label">Free Margin Available</div>
          <div class="metric-value" style="color: ${freeMargin > 0 ? '#34d399' : '#ef4444'};">$${freeMargin.toFixed(2)}</div>
        </div>
      </div>

      <div class="warning-box">
        ⚠️ <strong>Broker Action Warning:</strong> If the margin level drops toward the Stop-Out level (50%), the MT5 broker liquidity bridge will automatically trigger forced liquidation of open positions.
      </div>

      <a href="#" class="btn">Open Web Terminal & Manage Positions</a>
    </div>
    <div class="footer">
      Automated risk dispatch generated by Mthika Robot MT5 Autotrader &bull; Sent to ${recipient}
    </div>
  </div>
</body>
</html>
    `.trim(),
  };
}

export function createLargeLossEmail(
  recipient: string,
  pos: Position,
  currentBalance: number
): DispatchedEmail {
  const timestamp = Date.now();
  const dateStr = new Date(timestamp).toUTCString();
  const lossAbs = Math.abs(pos.pnlDollar).toFixed(2);
  const pipsAbs = Math.abs(pos.pnlPips).toFixed(1);

  return {
    id: `email-loss-${timestamp}-${Math.floor(Math.random() * 1000)}`,
    timestamp,
    recipient,
    subject: `⚠️ [LARGE LOSS ALERT] #${pos.ticket} ${pos.pairSymbol} closed with -$${lossAbs} (${pipsAbs} pips)`,
    event: 'LARGE_LOSS',
    severity: 'WARNING',
    status: 'DELIVERED',
    summary: `Position #${pos.ticket} (${pos.type} ${pos.lots} lots ${pos.pairSymbol}) closed at -$${lossAbs} (${pipsAbs} pips) due to ${pos.closeReason || 'STOP_LOSS'}.`,
    meta: {
      pairSymbol: pos.pairSymbol,
      amount: pos.pnlDollar,
      pips: pos.pnlPips,
      reason: pos.closeReason,
    },
    body: `
<!DOCTYPE html>
<html>
<head><style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #09090b; color: #f4f4f5; margin: 0; padding: 24px; }
  .card { max-width: 580px; margin: 0 auto; background: #18181b; border: 1px solid #f97316; border-radius: 12px; overflow: hidden; }
  .header { background: #431407; border-bottom: 1px solid #f97316; padding: 20px; }
  .badge { display: inline-block; background: #f97316; color: #fff; font-size: 11px; font-weight: bold; padding: 4px 10px; border-radius: 9999px; text-transform: uppercase; }
  .title { margin: 12px 0 4px 0; font-size: 20px; font-weight: bold; color: #ffffff; }
  .content { padding: 24px; font-size: 14px; line-height: 1.6; color: #d4d4d8; }
  .metric-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin: 20px 0; }
  .metric-box { background: #09090b; border: 1px solid #27272a; border-radius: 8px; padding: 12px; }
  .metric-label { font-size: 11px; color: #a1a1aa; text-transform: uppercase; letter-spacing: 0.5px; }
  .metric-value { font-size: 18px; font-weight: bold; margin-top: 4px; font-family: monospace; }
  .info-table { width: 100%; border-collapse: collapse; margin-top: 14px; font-size: 13px; }
  .info-table td { padding: 8px 4px; border-bottom: 1px solid #27272a; }
  .info-table td:first-child { color: #a1a1aa; }
  .info-table td:last-child { text-align: right; font-weight: 600; }
  .footer { border-top: 1px solid #27272a; padding: 16px 24px; font-size: 11px; color: #71717a; text-align: center; }
</style></head>
<body>
  <div class="card">
    <div class="header">
      <span class="badge">Risk Control Triggered</span>
      <div class="title">Large Loss Alert: -$${lossAbs}</div>
      <div style="font-size: 12px; color: #fdba74;">Trade Ticket #${pos.ticket} &bull; ${dateStr}</div>
    </div>
    <div class="content">
      <p>An automated trade has been closed that exceeded your defined <strong>Large Loss Protection Threshold</strong>.</p>
      
      <div class="metric-grid">
        <div class="metric-box">
          <div class="metric-label">Realized Loss</div>
          <div class="metric-value" style="color: #f87171;">-$${lossAbs}</div>
        </div>
        <div class="metric-box">
          <div class="metric-label">Pip Drawdown</div>
          <div class="metric-value" style="color: #f87171;">-${pipsAbs} pips</div>
        </div>
      </div>

      <table class="info-table">
        <tr><td>Instrument:</td><td>${pos.pairSymbol} (${pos.type})</td></tr>
        <tr><td>Volume:</td><td>${pos.lots} Lots</td></tr>
        <tr><td>Open Price:</td><td>${pos.openPrice}</td></tr>
        <tr><td>Exit Price:</td><td>${pos.closePrice || pos.currentPrice}</td></tr>
        <tr><td>Exit Trigger:</td><td>${pos.closeReason || 'STOP_LOSS'}</td></tr>
        <tr><td>Strategy Tag:</td><td>${pos.strategyName}</td></tr>
        <tr><td>Updated Account Balance:</td><td>$${currentBalance.toFixed(2)}</td></tr>
      </table>
    </div>
    <div class="footer">
      Automated risk dispatch generated by Mthika Robot MT5 Autotrader &bull; Sent to ${recipient}
    </div>
  </div>
</body>
</html>
    `.trim(),
  };
}

export function createStrategySwitchEmail(
  recipient: string,
  prevStrategyName: string,
  newStrategyName: string,
  details?: string
): DispatchedEmail {
  const timestamp = Date.now();
  const dateStr = new Date(timestamp).toUTCString();

  return {
    id: `email-strat-${timestamp}-${Math.floor(Math.random() * 1000)}`,
    timestamp,
    recipient,
    subject: `🔄 [STRATEGY SWITCHED] Trading Engine Switched to ${newStrategyName}`,
    event: 'STRATEGY_SWITCH',
    severity: 'INFO',
    status: 'DELIVERED',
    summary: `Active algorithmic strategy transitioned from "${prevStrategyName}" to "${newStrategyName}". Live signals and trade executions will now follow the new rule-set.`,
    meta: {
      prevStrategy: prevStrategyName,
      newStrategy: newStrategyName,
    },
    body: `
<!DOCTYPE html>
<html>
<head><style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #09090b; color: #f4f4f5; margin: 0; padding: 24px; }
  .card { max-width: 580px; margin: 0 auto; background: #18181b; border: 1px solid #06b6d4; border-radius: 12px; overflow: hidden; }
  .header { background: #083344; border-bottom: 1px solid #06b6d4; padding: 20px; }
  .badge { display: inline-block; background: #06b6d4; color: #000; font-size: 11px; font-weight: bold; padding: 4px 10px; border-radius: 9999px; text-transform: uppercase; }
  .title { margin: 12px 0 4px 0; font-size: 20px; font-weight: bold; color: #ffffff; }
  .content { padding: 24px; font-size: 14px; line-height: 1.6; color: #d4d4d8; }
  .switch-box { background: #09090b; border: 1px solid #27272a; border-radius: 8px; padding: 16px; margin: 16px 0; display: flex; align-items: center; justify-content: space-between; }
  .strat-name { font-weight: bold; font-size: 15px; color: #ffffff; }
  .details-box { background: #27272a; border-radius: 6px; padding: 12px 14px; font-size: 13px; color: #e4e4e7; margin-top: 12px; }
  .footer { border-top: 1px solid #27272a; padding: 16px 24px; font-size: 11px; color: #71717a; text-align: center; }
</style></head>
<body>
  <div class="card">
    <div class="header">
      <span class="badge">Execution Model Update</span>
      <div class="title">Active Strategy Switched</div>
      <div style="font-size: 12px; color: #a5f3fc;">System Audit Event &bull; ${dateStr}</div>
    </div>
    <div class="content">
      <p>This automated audit notification confirms that the active algorithmic trading strategy has been updated on your instance.</p>
      
      <div class="switch-box">
        <div>
          <div style="font-size: 11px; color: #71717a; text-transform: uppercase;">Previous Model</div>
          <div class="strat-name" style="color: #a1a1aa;">${prevStrategyName}</div>
        </div>
        <div style="font-size: 20px; color: #06b6d4; padding: 0 16px;">➔</div>
        <div>
          <div style="font-size: 11px; color: #06b6d4; text-transform: uppercase;">Active Model</div>
          <div class="strat-name" style="color: #22d3ee;">${newStrategyName}</div>
        </div>
      </div>

      ${
        details
          ? `<div class="details-box"><strong>Configuration Notes:</strong><br/>${details}</div>`
          : ''
      }

      <p style="font-size: 13px; color: #a1a1aa; margin-top: 16px;">
        All subsequent order evaluations, technical indicator confluence checks, and automated entries will execute according to the rules of <strong>${newStrategyName}</strong>.
      </p>
    </div>
    <div class="footer">
      Automated audit notification generated by Mthika Robot MT5 Autotrader &bull; Sent to ${recipient}
    </div>
  </div>
</body>
</html>
    `.trim(),
  };
}

export function createPanicStopEmail(
  recipient: string,
  reason: string,
  closedTradesCount: number,
  balance: number
): DispatchedEmail {
  const timestamp = Date.now();
  const dateStr = new Date(timestamp).toUTCString();

  return {
    id: `email-panic-${timestamp}-${Math.floor(Math.random() * 1000)}`,
    timestamp,
    recipient,
    subject: `🛑 [EMERGENCY HALT] Trading Robot Halted & Positions Closed (${reason})`,
    event: 'PANIC_STOP',
    severity: 'CRITICAL',
    status: 'DELIVERED',
    summary: `Emergency halt triggered (${reason}). Auto-trading robot paused and ${closedTradesCount} active positions liquidated. Current Balance: $${balance.toFixed(2)}.`,
    meta: {
      amount: balance,
      reason,
    },
    body: `
<!DOCTYPE html>
<html>
<head><style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #09090b; color: #f4f4f5; margin: 0; padding: 24px; }
  .card { max-width: 580px; margin: 0 auto; background: #18181b; border: 1px solid #f43f5e; border-radius: 12px; overflow: hidden; }
  .header { background: #4c0519; border-bottom: 1px solid #f43f5e; padding: 20px; }
  .badge { display: inline-block; background: #f43f5e; color: #fff; font-size: 11px; font-weight: bold; padding: 4px 10px; border-radius: 9999px; text-transform: uppercase; }
  .title { margin: 12px 0 4px 0; font-size: 20px; font-weight: bold; color: #ffffff; }
  .content { padding: 24px; font-size: 14px; line-height: 1.6; color: #d4d4d8; }
  .footer { border-top: 1px solid #27272a; padding: 16px 24px; font-size: 11px; color: #71717a; text-align: center; }
</style></head>
<body>
  <div class="card">
    <div class="header">
      <span class="badge">Safety Circuit Breaker</span>
      <div class="title">Trading Robot Halted</div>
      <div style="font-size: 12px; color: #fecdd3;">Emergency Event &bull; ${dateStr}</div>
    </div>
    <div class="content">
      <p>An emergency stop has executed on your account. The automated robot has been switched to <strong>STOPPED</strong> and market orders have been liquidated to safeguard your account capital.</p>
      
      <div style="background: #09090b; border: 1px solid #27272a; border-radius: 8px; padding: 16px; margin: 16px 0;">
        <div style="font-size: 13px; color: #a1a1aa;">Trigger Triggered: <strong style="color: #ffffff;">${reason}</strong></div>
        <div style="font-size: 13px; color: #a1a1aa; margin-top: 6px;">Liquidated Positions: <strong style="color: #ffffff;">${closedTradesCount}</strong></div>
        <div style="font-size: 13px; color: #a1a1aa; margin-top: 6px;">Preserved Balance: <strong style="color: #34d399;">$${balance.toFixed(2)}</strong></div>
      </div>
    </div>
    <div class="footer">
      Automated risk dispatch generated by Mthika Robot MT5 Autotrader &bull; Sent to ${recipient}
    </div>
  </div>
</body>
</html>
    `.trim(),
  };
}

export function createTestEmail(
  recipient: string,
  eventType: 'MARGIN_CALL' | 'LARGE_LOSS' | 'STRATEGY_SWITCH' | 'TEST_EMAIL'
): DispatchedEmail {
  const timestamp = Date.now();
  const dateStr = new Date(timestamp).toUTCString();

  if (eventType === 'MARGIN_CALL') {
    return createMarginCallEmail(recipient, 92, 920.0, 1000.0, 0);
  }

  if (eventType === 'LARGE_LOSS') {
    const dummyPos: Position = {
      id: 'test-pos',
      ticket: 19842,
      pairSymbol: 'EUR/USD',
      type: 'BUY',
      lots: 0.2,
      openPrice: 1.0850,
      currentPrice: 1.0825,
      closePrice: 1.0825,
      stopLoss: 1.0825,
      takeProfit: 1.0890,
      trailingStopPips: null,
      pnlDollar: -50.0,
      pnlPips: -25.0,
      openTime: timestamp - 300000,
      closeTime: timestamp,
      closeReason: 'STOP_LOSS',
      strategyName: 'London Trend (EMA Cross)',
    };
    return createLargeLossEmail(recipient, dummyPos, 9950.0);
  }

  if (eventType === 'STRATEGY_SWITCH') {
    return createStrategySwitchEmail(
      recipient,
      'London Trend (EMA 9/21/50)',
      'Forex Copy Scalper Robot (HFT Micro)',
      'Timeframe: 1M &bull; Dynamic Lot Sizing &bull; Trailing Stop 5 Pips'
    );
  }

  return {
    id: `email-test-${timestamp}-${Math.floor(Math.random() * 1000)}`,
    timestamp,
    recipient,
    subject: `✅ [TEST NOTIFICATION] Mthika Robot Email Alert Delivery Confirmation`,
    event: 'TEST_EMAIL',
    severity: 'INFO',
    status: 'DELIVERED',
    summary: `Test notification successfully dispatched to ${recipient}. Email integration is verified and operational.`,
    body: `
<!DOCTYPE html>
<html>
<head><style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #09090b; color: #f4f4f5; margin: 0; padding: 24px; }
  .card { max-width: 580px; margin: 0 auto; background: #18181b; border: 1px solid #10b981; border-radius: 12px; overflow: hidden; }
  .header { background: #064e3b; border-bottom: 1px solid #10b981; padding: 20px; }
  .badge { display: inline-block; background: #10b981; color: #000; font-size: 11px; font-weight: bold; padding: 4px 10px; border-radius: 9999px; text-transform: uppercase; }
  .title { margin: 12px 0 4px 0; font-size: 20px; font-weight: bold; color: #ffffff; }
  .content { padding: 24px; font-size: 14px; line-height: 1.6; color: #d4d4d8; }
  .footer { border-top: 1px solid #27272a; padding: 16px 24px; font-size: 11px; color: #71717a; text-align: center; }
</style></head>
<body>
  <div class="card">
    <div class="header">
      <span class="badge">Connection Verified</span>
      <div class="title">Email Alerts Operational</div>
      <div style="font-size: 12px; color: #a7f3d0;">Test Dispatch &bull; ${dateStr}</div>
    </div>
    <div class="content">
      <p>Congratulations! Your email notification settings are correctly configured for <strong>${recipient}</strong>.</p>
      <p>You will receive instant, critical alerts whenever any of the following occur:</p>
      <ul>
        <li><strong>Margin Call Alerts:</strong> When account margin level drops below your threshold</li>
        <li><strong>Large Loss Protection:</strong> When any trade closes exceeding your loss limit</li>
        <li><strong>Strategy Switches:</strong> When algorithmic parameters or active strategies change</li>
        <li><strong>Panic Circuit Breakers:</strong> When emergency stops are activated</li>
      </ul>
    </div>
    <div class="footer">
      Automated test dispatch generated by Mthika Robot MT5 Autotrader &bull; Sent to ${recipient}
    </div>
  </div>
</body>
</html>
    `.trim(),
  };
}
